CC ?= cc
CFLAGS ?= -O3 -std=c99 -Wall -Wextra -Wpedantic
FRAMA_C ?= frama-c
CLANG_FORMAT := $(shell command -v clang-format-20 2>/dev/null || \
	command -v clang-format 2>/dev/null)
C_SOURCES := $(wildcard *.c *.h)
SAMPLE_STATE := 21345671111111
SAMPLE_SOLUTION := B' R' D2 R' B R B' R D2 B R'
VECTORS := tests/solutions.txt
# One per rejection path: short, long, cubie digit low, cubie digit high,
# orientation digit low, orientation digit high, non-digit, duplicate, parity.
INVALID_STATES := 1234567111111 123456711111111 02345671111111 82345671111111 \
	12345671111110 12345671111114 1234567111111a 11345671111111 12345671111112

.PHONY: all check gates ripes-check ripes-sweep prove clean indent cases.s

RIPES ?= ripes
# Test cases for the assembly build, as state:expected-length (-1: unknown).
# Solved, a 3-move scramble (R B' D2), and the reference distance-11 vector.
CASES ?= 12345671111111:0 24173562322133:3 21345671111111:11

all: solver mini ida

# gen checks gates H1 and H2 before it writes tables.h, tables.s and the
# list of distance-11 states.
tables.h tables.s distance11.txt: gen
	./gen

gen: gen.c solver.c
	$(CC) $(CFLAGS) $< -o $@

ida: ida.c tables.h
	$(CC) $(CFLAGS) $< -o $@

# The state strings are inlined at assembly time, before the table that
# points at them: Ripes resolves .word symbols only backwards. Each string
# is padded to 16 bytes so the table stays word-aligned without .align,
# which means 2^n bytes to GNU as but n bytes to Ripes. A state given
# without ":length" is checked only for reaching solved (length -1).
cases.s:
	@{ echo '# Generated by make; do not edit.'; i=0; \
	for c in $(CASES); do echo "case$$i: .string \"$${c%%:*}\""; \
	echo '    .byte 0'; i=$$((i+1)); done; echo 'cases:'; i=0; \
	for c in $(CASES); do case $$c in *:*) n=$${c#*:};; *) n=-1;; esac; \
	echo "    .word case$$i, $$n"; i=$$((i+1)); done; \
	echo '    .word 0, 0'; } > $@

# One source, two builds: they differ only in the .if RENDER blocks.
rubik-cli.s: rubik.s asmpp.awk tables.h tables.s cases.s
	awk -v RENDER=0 -f asmpp.awk $< > $@

rubik-gui.s: rubik.s asmpp.awk tables.h tables.s cases.s render.s
	awk -v RENDER=1 -f asmpp.awk $< > $@

# T5-T7 on the target: the test cases on the ISS and two pipelined models.
# Each run validates its own results and exits non-zero on a failure.
ripes-check: rubik-cli.s
	@for proc in RV32_ISS RV32_5S RV32_6S_DUAL; do \
		echo "== $$proc"; \
		$(RIPES) --mode cli -t asm --src rubik-cli.s --proc $$proc \
			--iret --cycles || exit 1; \
	done

# The pass condition: every distance-11 state under 5e7 on RV32_ISS.
ripes-sweep: tables.h
	RIPES=$(RIPES) ./ripes-sweep.sh > sweep.txt

gates: gates.c ida.c solver.c tables.h
	$(CC) $(CFLAGS) $< -o $@
	./gates

solver: solver.c
	$(CC) $(CFLAGS) $< -o $@

mini: mini.c
	$(CC) $(CFLAGS) $< -o $@

check: solver mini $(VECTORS)
	./solver --self-test
	@expected=$$(mktemp); actual=$$(mktemp); \
		trap 'rm -f "$$expected" "$$actual"' 0 1 2 15; \
		count=0; \
		while IFS='|' read -r state solution; do \
			case "$$state" in ""|\#*) continue ;; esac; \
			printf '%s\n' "$$solution" >"$$expected"; \
			for binary in ./solver ./mini; do \
				$$binary "$$state" >"$$actual"; \
				status=$$?; \
				test $$status -eq 0 || { \
					echo "$$binary $$state: exit status $$status"; exit 1; }; \
				cmp -s "$$actual" "$$expected" || { \
					echo "$$binary $$state: output mismatch"; \
					echo "  expected: $$solution"; \
					printf '  got:      '; cat "$$actual"; \
					echo "  ($$(wc -c <"$$expected") bytes expected, \
$$(wc -c <"$$actual") produced)"; exit 1; }; \
			done; \
			count=$$((count + 1)); \
		done <$(VECTORS); \
		echo "$$count solution vectors matched by solver and mini"
	@for binary in ./solver ./mini; do \
		for bad in $(INVALID_STATES); do \
			$$binary "$$bad" >/dev/null 2>&1; \
			status=$$?; \
			test $$status -eq 2 || { \
				echo "$$binary $$bad: expected status 2, got $$status"; exit 1; }; \
		done; \
		$$binary >/dev/null 2>&1; \
		status=$$?; \
		test $$status -eq 2 || { \
			echo "$$binary with no argument: expected status 2, got $$status"; \
			exit 1; }; \
		$$binary $(SAMPLE_STATE) $(SAMPLE_STATE) >/dev/null 2>&1; \
		status=$$?; \
		test $$status -eq 2 || { \
			echo "$$binary with two arguments: expected status 2, got $$status"; \
			exit 1; }; \
		$$binary $(SAMPLE_STATE) >&- 2>/dev/null; \
		status=$$?; \
		test $$status -eq 1 || { \
			echo "$$binary with stdout closed: expected status 1, got $$status"; \
			exit 1; }; \
	done
	@./solver --self-test >&- 2>/dev/null; \
		status=$$?; \
		test $$status -eq 1 || { \
			echo "solver --self-test with stdout closed: expected 1, got $$status"; \
			exit 1; }
	@echo "invalid input rejected with status 2, unwritable stdout with status 1"

prove: solver.c
	@log=$$(mktemp); trap 'rm -f "$$log"' 0 1 2 15; \
		$(FRAMA_C) -wp -wp-fct quarter_turn,rank_state,valid,parse_state \
		-wp-rte -rte-verbose 0 -wp-prover alt-ergo -wp-timeout 20 \
		-wp-cache none solver.c >"$$log" 2>&1; rc=$$?; \
		grep -Fvx -e '[wp] Warning: Skipped RTE guards: unaligned pointers (\aligned not supported)' \
		-e '[wp] Warning: Skipped RTE guards: invalid function pointer calls (\valid_function not supported)' "$$log"; \
		test $$rc -eq 0 && awk '$$1 == "[wp]" && $$2 == "Proved" && $$3 == "goals:" && $$4 > 0 && $$4 == $$6 { ok = 1 } END { exit !ok }' "$$log" && \
		! grep -Eq '(^|[[:space:]])(Timeout|Unknown|Failed):' "$$log"

indent:
ifeq ($(CLANG_FORMAT),)
	$(error clang-format 20 not found)
endif
	@$(CLANG_FORMAT) --version | grep -q 'version 20' || \
		{ echo "error: clang-format version 20 required"; exit 1; }
	$(CLANG_FORMAT) -i $(C_SOURCES)

clean:
	$(RM) solver mini gen ida gates tables.h tables.s cases.s rubik-cli.s rubik-gui.s \
		distance11.txt sweep.txt
